// Generate csrc/kl_norm_data.c -- the normalization tables kl_norm.c reads.
//
//   node tools/build-norm-c.mjs            write the file
//   node tools/build-norm-c.mjs --check    fail if what is on disk is stale
//
// The source of truth is the same ICU the JavaScript engine's
// String.prototype.normalize('NFKC') uses, so the table cannot disagree with
// the reference implementation by construction -- the same argument that
// makes tools/build-banks-c.mjs safe. It can still go stale if Node's ICU
// moves, which is what --check is for; it runs in ctest and in CI.
//
// Only *singleton* NFKC mappings are emitted: one code point in, a string
// out. Canonical composition and reordering are deliberately absent, and
// docs/16-stage4-token.md carries the measurement that bounds what that can
// cost -- of 12,236 code points with a multi-character NFD, none is ASCII and
// none is whitespace, and no ASCII code point is moved by NFKC or NFD at all.
// So composition can never produce a character this grammar reads.

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'csrc', 'kl_norm_data.c');

// Mirrors of the two tables in src/engine/sequencer.js. They are small and
// hand-written there, so they are hand-written here and checked against the
// engine below rather than parsed out of it.
const HOMOGLYPH_MAP = {
  'Α':'A','Β':'B','Ε':'E','Η':'H','Ι':'I','Κ':'K','Μ':'M','Ν':'N','Ο':'O','Ρ':'P','Τ':'T','Υ':'Y','Ζ':'Z',
  'А':'A','В':'B','С':'C','Е':'E','Н':'H','К':'K','М':'M','О':'O','Р':'P','Т':'T',
  'а':'a','с':'c','е':'e','о':'o','р':'p',
};
const ZERO_WIDTH = [0x200B, 0x200C, 0x200D, 0x2060, 0xFEFF];

// Cross-check against the engine, so a change there is caught here rather
// than becoming a silent divergence between the two normalizers.
const seqSrc = readFileSync(join(root, 'src', 'engine', 'sequencer.js'), 'utf8');
for (const [from, to] of Object.entries(HOMOGLYPH_MAP)) {
  if (!seqSrc.includes(`'${from}':'${to}'`)) {
    throw new Error(`homoglyph ${from}->${to} is in this generator but not in sequencer.js`);
  }
}
const hgCount = (seqSrc.match(/'[^']':'[A-Za-z]'/g) ?? []).length;
if (hgCount !== Object.keys(HOMOGLYPH_MAP).length) {
  throw new Error(`sequencer.js has ${hgCount} homoglyph entries, this generator has ${Object.keys(HOMOGLYPH_MAP).length}`);
}
for (const cp of ZERO_WIDTH) {
  if (!seqSrc.includes('0x' + cp.toString(16).toUpperCase().padStart(4, '0'))) {
    throw new Error(`zero-width U+${cp.toString(16)} is in this generator but not in sequencer.js`);
  }
}

// Walk all of Unicode and keep every code point NFKC moves.
const entries = [];
const pool = [];
let maxLen = 0;
for (let cp = 0; cp <= 0x10FFFF; cp++) {
  if (cp >= 0xD800 && cp <= 0xDFFF) continue;         // lone surrogates
  const s = String.fromCodePoint(cp);
  const n = s.normalize('NFKC');
  if (n === s) continue;
  const units = [];
  for (let i = 0; i < n.length; i++) units.push(n.charCodeAt(i));   // UTF-16, as JS sees it
  if (units.length > maxLen) maxLen = units.length;
  entries.push({ cp, off: pool.length, len: units.length });
  pool.push(...units);
}

const hex4 = (n) => '0x' + n.toString(16).toUpperCase().padStart(4, '0');
const lines = [];
const P = (s = '') => lines.push(s);

P('/* Generated by tools/build-norm-c.mjs -- do not edit by hand.');
P(' *');
P(' * NFKC singleton mappings, taken from the same ICU that backs');
P(" * String.prototype.normalize('NFKC') in the reference JavaScript engine.");
P(' * Canonical composition and reordering are deliberately not here; see');
P(' * docs/16-stage4-token.md for the measurement that bounds what that costs.');
P(' *');
P(' * klattsch is Tony Gies\'s work, MIT licensed. This file is generated from');
P(' * Unicode data, not from his source, but it exists to serve a translation of');
P(' * it and travels under the same notice.');
P(' */');
P('');
P('#include "kl_norm.h"');
P('');
P(`/* ${entries.length} code points move under NFKC; longest expansion ${maxLen} UTF-16 units. */`);
P(`const uint16_t kl_norm_pool[${pool.length}] = {`);
for (let i = 0; i < pool.length; i += 12) {
  P('    ' + pool.slice(i, i + 12).map(hex4).join(', ') + ',');
}
P('};');
P('');
P(`const kl_norm_entry kl_norm_table[${entries.length}] = {`);
for (const e of entries) {
  P(`    { 0x${e.cp.toString(16).toUpperCase().padStart(5, '0')}, ${e.off}, ${e.len} },`);
}
P('};');
P('');
P(`const size_t kl_norm_table_len = ${entries.length};`);
P('');
P('/* Stripped outright, before the homoglyph pass. */');
P(`const uint16_t kl_zero_width[${ZERO_WIDTH.length}] = { ${ZERO_WIDTH.map(hex4).join(', ')} };`);
P(`const size_t kl_zero_width_len = ${ZERO_WIDTH.length};`);
P('');
const hg = Object.entries(HOMOGLYPH_MAP).sort((a, b) => a[0].codePointAt(0) - b[0].codePointAt(0));
P('/* Greek and Cyrillic letters that look Latin. Applied last, as in the JS. */');
P(`const kl_homoglyph kl_homoglyph_table[${hg.length}] = {`);
for (const [from, to] of hg) {
  P(`    { ${hex4(from.codePointAt(0))}, '${to}' },`);
}
P('};');
P(`const size_t kl_homoglyph_table_len = ${hg.length};`);
P('');

const text = lines.join('\n');
const digest = createHash('sha256').update(text, 'utf8').digest('hex');

if (process.argv.includes('--check')) {
  let onDisk;
  try { onDisk = readFileSync(out, 'utf8'); }
  catch { process.stderr.write('kl_norm_data.c is missing; run: node tools/build-norm-c.mjs\n'); process.exit(1); }
  // Compare content, not bytes: the working tree may hold CRLF on Windows
  // while the repository holds LF. That false positive cost an afternoon
  // once already -- see docs/ROADMAP.md, phase 2 prerequisites.
  if (onDisk.replace(/\r\n/g, '\n') !== text) {
    process.stderr.write('kl_norm_data.c is stale -- Node\'s ICU has moved, or the tables in sequencer.js have.\n'
      + 'Re-run: node tools/build-norm-c.mjs, and review the diff before committing it.\n');
    process.exit(1);
  }
  process.stdout.write(`kl_norm_data.c current  ${entries.length} NFKC mappings, ${pool.length} pool units  ${digest.slice(0, 16)}\n`);
  process.exit(0);
}

writeFileSync(out, text, 'utf8');
process.stdout.write(
  `wrote csrc/kl_norm_data.c\n`
  + `  NFKC singleton mappings  ${entries.length}\n`
  + `  UTF-16 pool units        ${pool.length}\n`
  + `  longest expansion        ${maxLen}\n`
  + `  zero-width stripped      ${ZERO_WIDTH.length}\n`
  + `  homoglyphs               ${hg.length}\n`
  + `  sha256                   ${digest}\n`);
